version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    kubernetes:
      patterns:
      - "k8s.io"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "daily"