---
before:
  hooks:
  - go mod tidy -compat=1.17

builds:
  - id: demo-app
    goos: &goos-defs
      - linux
      - darwin
      - windows
    goarch: &goarch-defs
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
    binary: demo-app
    ldflags:
      - "-X main.buildVersion={{.Version}} -X main.buildCommit={{.ShortCommit}}"

archives:
  - id: demo-app
    builds:
      - demo-app
    name_template: "demo-app_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "{{ .Tag }}-next"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch

brews:
  - name: demo-app
    ids:
      - demo-app
    repository:
      owner: embano1
      name: homebrew-ci-demo-app
      # needs repo permissions on target, eg using PAT
      token: "{{ .Env.GORELEASER_TOKEN }}"
    commit_author:
      name: Michael Gasch
      email: michael@mgasch.com
    folder: Formula
    homepage: "https://github.com/embano1/ci-demo-app/blob/master/README.md"
    description: "Go CI Demo App showcasing goreleaser, Github Actions and ko."
    test: |
      system "#{bin}/demo-app version"
    install: |
      bin.install "demo-app"
    skip_upload: "false"

# unused because we use ko for this job
# dockers: