builds:
- id: app
  # dir: .
  # main: .
  env:
  - GOPRIVATE=*.vmware.com
  flags:
  - -tags
  - netgo
  - -mod=mod
  - -v
  ldflags:
  - -s -w
  - -extldflags "-static"
  # - -X main.buildCommit={{.Env.KO_COMMIT}}
  # - -X main.buildVersion={{.Env.KO_TAG}}