attest:
  cocosign:
    policies:
    - name: marsh_policy
      enable: true
      modules:

        - name: signed_image_SLSA_prov
          type: verify-artifact # Verify artifact Origin and Source
          enable: true
          input:
            signed: true
            format: attest-slsa
            identity:
              uris:
                - https://github.com/scribe-security/ci-demo-app/.github/workflows/release.yaml@refs/heads/marsh
            match:
              target_type: image

        - name: signed_sources_SBOMs
          type: verify-artifact # Verify artifact Origin and Source
          enable: true
          input:
            signed: true
            format: attest
            identity:
              uris:
                - https://github.com/scribe-security/ci-demo-app/.github/workflows/reusable-checkout-sign.yaml@refs/heads/marsh
            match:
              target_type: git
              target_git_url: https://github.com/scribe-security/ci-demo-app.git
                    
        - name: verify_git_owners
          type: git-scm-rule 
          enable: true
          input:
            signed_commits: false
            match:
              target_git_url: https://github.com/scribe-security/ci-demo-app.git
              target_git_branch: main
              format: attest-cyclonedx-json
            admin:
            - mgasch@vmware.com
            - mdstrauss91@gmail.com
            specific:
            - path: "CHANGELOG.md"
              owners:
              - embano1@users.noreply.github.com