attest:
  cocosign:
    policies:
    - name: marsh_policy
      enable: true
      modules:

        - name: signed_image_SLSA_prov
          type: verify-artifact # Verify artifact Origin and Source
          enable: true
          input:
            signed: true
            format: attest-slsa
              uris:
                - https://github.com/scribe-security/ci-demo-app/.github/workflows/reusable-checkout-sign.yaml@refs/heads/marsh
            match:
              target_type: image

        - name: signed_sources_SBOMs
          type: verify-artifact # Verify artifact Origin and Source
          enable: true
          input:
            signed: true
            format: attest
            identity:
              uris:
                - https://github.com/scribe-security/ci-demo-app/.github/workflows/reusable-checkout-sign.yaml@refs/heads/marsh
            match:
              target_type: git
              target_git_url: https://github.com/scribe-security/ci-demo-app.git
                    