apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: demo-app
spec:
  template:
    spec:
      containers:
        - image: ko://github.com/scribe-security/ci-demo-app
          readinessProbe:
            httpGet:
              path: /healthz