name: Build

on:
  push:
    branches: ["main", "master"]

  pull_request:
    branches: ["main", "master", "release-*"]
  
  workflow_dispatch:

jobs:
  artifacts:
    name: Create Artifacts (no push/upload)
    timeout-minutes: 10
    strategy:
      matrix:
        go-version: ["1.17"]
        platform: ["ubuntu-latest"]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Restore go cache
        id: go-cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ env.GO_VERSION }}-

      - name: REMOVE - check library
        run: |
          FILES=`find -O3 -L ~/go/pkg/mod/go.uber.org/zap* -name "sugar.go"`
          for file in $FILES
          do
            echo ############## $file #####################
            cat $file | grep -A 10 "Infow(msg"
          done

      - name: Create CHANGELOG
        run: |
          # build from vendor
          go build -mod=vendor github.com/git-chglog/git-chglog/cmd/git-chglog

          # use a pseudo tag to only include changes since last release
          NEXT_TAG=$(git describe --abbrev=0 --tags)-next

          # generate CHANGELOG
          ./git-chglog --next-tag ${NEXT_TAG} -o RELEASE_CHANGELOG.md ${NEXT_TAG}

      - name: Archive CHANGELOG
        uses: actions/upload-artifact@v2
        with:
          name: CHANGELOG
          path: |
            ./RELEASE_CHANGELOG.md
          retention-days: 1

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # no push
          args: release --rm-dist --snapshot --release-notes RELEASE_CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GORELEASER_TOKEN: ${{ secrets.GORELEASER_TOKEN }}

      - name: Verify git clean
        shell: bash
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "${{ github.repository }} up to date."
          else
            echo "${{ github.repository }} is dirty."
            echo "::error:: $(git status)"
            exit 1
          fi

      - name: BAD ACTION - Cahnge library in cache
        run: |
          who
          groups
          ls -lh  ~/go/pkg/mod/go.uber.org
          find -L ~/go/pkg/mod/go.uber.org/* -name "sugar.go"
          find -O3 -L ~/go/pkg/mod/go.uber.org/zap* -name "sugar.go"
          ls -lh /home/runner/go/pkg/mod/go.uber.org/zap@v1.16.0/sugar.go
          FILES=`find -O3 -L ~/go/pkg/mod/go.uber.org/zap* -name "sugar.go"`
          for file in $FILES
          do
            echo ############## $file #####################
            sed -i 's/s.log(InfoLevel, msg, nil, keysAndValues)/s.log(InfoLevel, msg + "BAD library", nil, keysAndValues)/g' $file || true
          done
          sed -i 's/s.log(InfoLevel, msg, nil, keysAndValues)/s.log(InfoLevel, msg + "BAD library", nil, keysAndValues)/g' /home/runner/go/pkg/mod/go.uber.org/zap@v1.16.0/sugar.go || true

      # - name: BAD ACTION - Push cache
      #   id: go-cache
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/go/pkg/mod
      #     key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-badcache
          # restore-keys: |
          #   ${{ runner.os }}-go-${{ env.GO_VERSION }}-

      - name: Archive goreleaser artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/demo-app*x86_64*.tar.gz
            dist/checksums.txt
          retention-days: 1

  release:
    needs: artifacts
    name: Build ko Artifact and Docker Image (no push)
    timeout-minutes: 10
    env:
      KO_DOCKER_REPO: docker.io/embano1
    strategy:
      matrix:
        go-version: ["1.17"]
        platform: ["ubuntu-latest"]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Restore go cache
        id: go-cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ env.GO_VERSION }}-

      - name: Setup ko
        uses: imjasonh/setup-ko@2c3450ca27f6e6f2b02e72a40f2163c281a1f675 # v0.4 tag, will install latest ko version

      - name: Check out code onto GOPATH
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Get short COMMIT and TAG
        run: |
          echo "KO_COMMIT=$(echo -n $GITHUB_SHA | cut -c -8)" >> $GITHUB_ENV
          echo "KO_TAG=$(basename "${{ github.ref }}")" >> $GITHUB_ENV

      - name: Build Images (amd64 only)
        run: |
          ko resolve --tags ${KO_TAG},${KO_COMMIT},latest --push=false -BRf config/ > release.yaml

      - name: Archive ko artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: |
            ./release.yaml
          retention-days: 1
