name: checkout-sign

on:
  push:
    branches: ["main", "master"]
    # tags:
    #   - "v*"

  pull_request:
    branches: ["main", "master", "release-*"]
  
  workflow_dispatch:

jobs:
  checkout-sign:
    name: Checkout sign
    timeout-minutes: 10
    strategy:
      matrix:
        platform: ["ubuntu-latest"]
    runs-on: ${{ matrix.platform }}
    permissions:
      actions: none
      checks: none
      contents: read
      deployments: none
      issues: none
      packages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
      id-token: write

    steps:
      - name: SIGN - Checkout
        if: "contains(github.event.head_commit.message, 'sign')"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Restore checkout signatures cache
        id: checkout-sign-cache
        uses: actions/cache@v2
        with:
          path: bomber_reports
          key: checkout-${{ github.sha }}

      - name: Check for old signature in cache
        if: steps.checkout-sign-cache.outputs.cache-hit == 'true'
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('Signature should not be present in cache')

      - name: SIGN - Bomber attest src
        if: "contains(github.event.head_commit.message, 'sign')"
        id: bomber_attest
        uses: scribe-security/bomber-action/bomb-syft@v20
        with:
           type: dir
           target: /github/workspace/
           verbose: 3
           format: attest
           attest-name: checkout
           attest-config: config/.cocosign.yaml

      # - name: SIGN - Archive bomber signature
      #   if: "contains(github.event.head_commit.message, 'sign')"
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: bomber-signatures
      #     path: |
      #       bomber_reports
      #     retention-days: 1
