name: checkout

on:
  push:
    branches: ["main", "master"]
    tags:
      - "v*"

  pull_request:
    branches: ["main", "master", "release-*"]
  
  workflow_dispatch:

jobs:
  checkout-sign:
    name: Checkout sign
    timeout-minutes: 10
    strategy:
      matrix:
        platform: ["ubuntu-latest"]
    runs-on: ${{ matrix.platform }}
    permissions:
      actions: none
      checks: none
      contents: read
      deployments: none
      issues: none
      packages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bomber attest src
        # if: "contains(github.event.head_commit.message, 'sign')"
        id: bomber_attest
        uses: scribe-security/bomber-action/bomb-syft@v20
        with:
           type: dir
           target: '${GITHUB_WORKSPACE}'
           verbose: 3
           format: attest
           attest-config: config/.cocosign.yaml

      # - name: Restore go cache
      #   id: go-cache
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/go/pkg/mod
      #     key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}

      - name: Archive bomber signature
      # if: "contains(github.event.head_commit.message, 'sign')"

        uses: actions/upload-artifact@v2
        with:
          name: bomber-signatures
          path: |
            bomber_reports