# Perform "exit 1" if PR title starts with "WIP" to block accidental merges
name: Check "WIP" in PR Title

on:
  # push:
  #   branches: ["main", "master"]
#   pull_request:
#     types: [opened, synchronize, reopened, edited]
  workflow_dispatch:

jobs:
  wip:
    runs-on: ubuntu-latest
    steps:
      - name: Check WIP in PR Title
        uses: embano1/wip@v1