name: E2E Tests

on:
  push:
    branches: ["main", "master"]

  pull_request:
    branches: ["main", "master", "release-*"]

jobs:
  ko-resolve:
    name: e2e tests
    strategy:
      matrix:
        go-version: ["1.18"]
        platform: ["ubuntu-latest"]
    runs-on: ${{ matrix.platform }}
    env:
      KO_DOCKER_REPO: kind.local
      KIND_CLUSTER_NAME: e2e
      NAMESPACE: "demo-app"
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Setup ko
      uses: imjasonh/setup-ko@78eea08f10db87a7a23a666a4a6fe2734f2eeb8d # will install latest ko version

    - name: Setup KinD Cluster
      env:
        KIND_VERSION: v0.12.0
        NODE_VERSION: v1.23.5
        NODE_SHA: sha256:a69c29d3d502635369a5fe92d8e503c09581fcd406ba6598acc5d80ff5ba81b1
      run: |
        set -x
        curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-$(uname)-amd64
        chmod +x ./kind
        sudo mv kind /usr/local/bin

        # KinD configuration.
        cat > kind.yaml <<EOF
        apiVersion: kind.x-k8s.io/v1alpha4
        kind: Cluster
        nodes:
        - role: control-plane
          image: kindest/node:${NODE_VERSION}@${NODE_SHA}
        - role: worker
          image: kindest/node:${NODE_VERSION}@${NODE_SHA}
        EOF

        # Create a cluster!
        kind create cluster --config kind.yaml --wait 3m --name ${KIND_CLUSTER_NAME}

    - name: Setup Knative Serving
      env:
        KNATIVE_VERSION: knative-v1.4.0
      run: |
        echo "::group::Serving CRDs"
        kubectl apply -f https://github.com/knative/serving/releases/download/${KNATIVE_VERSION}/serving-crds.yaml
        kubectl wait --timeout=20s --for=condition=Established crd/services.serving.knative.dev
        echo "::endgroup::"

        echo "::group::Serving Core"
        kubectl apply -f https://github.com/knative/serving/releases/download/${KNATIVE_VERSION}/serving-core.yaml
        kubectl -n knative-serving wait --timeout=2m --for=condition=Available deploy/webhook
        echo "::endgroup::"

        echo "::group::Ingress"
        echo "waiting 10s before proceeding..." && sleep 10 # hack: give webhook mutating admission controllers some time to settle
        kubectl apply -f https://github.com/knative/net-kourier/releases/download/${KNATIVE_VERSION}/kourier.yaml
        kubectl -n kourier-system wait --timeout=2m --for=condition=Available deploy/3scale-kourier-gateway
        kubectl patch configmap/config-network \
        --namespace knative-serving \
        --type merge \
        --patch '{"data":{"ingress.class":"kourier.ingress.networking.knative.dev"}}'
        echo "::endgroup::"

    - name: "Upload Test Images"
      run: ./test/upload_test_images.sh

    - name: Get short COMMIT and TAG (used by ko)
      run: |
        echo "KO_COMMIT=$(echo -n $GITHUB_SHA | cut -c -8)" >> $GITHUB_ENV
        echo "KO_TAG=$(basename "${{ github.ref }}")" >> $GITHUB_ENV

    - name: "Deploy Server App"
      run: |
        kubectl create ns ${NAMESPACE}
        ko resolve -BR -f config/ | kubectl -n ${NAMESPACE} apply -f -
        kubectl -n ${NAMESPACE} wait --timeout=2m --for=condition=Ready ksvc/demo-app

    - name: "Run E2E Tests"
      env:
        TESTFLAGS: "-timeout 1m -v -tags=e2e -count 1 -race"

      run: |
        go test ${TESTFLAGS} ./test/...

    - name: "Debug"
      if: ${{ always() }}
      run: |
        kubectl get pods --all-namespaces
        kubectl -n ${NAMESPACE} describe pods
        kubectl -n ${NAMESPACE} get events

    - name: Collect diagnostics
      uses: chainguard-dev/actions/kind-diag@main
      # Only upload logs on failure.
      if: ${{ failure() }}
      with:
        cluster-resources: nodes
        namespace-resources: pods,svc
        artifact-name: logs