name: Code Linting

on:
  push:
    branches: ["main", "master"]

  pull_request:
    branches: ["main", "master", "release-*"]

jobs:
  lint:
    name: Code Linting
    strategy:
      matrix:
        go-version: ["1.18"]
        platform: ["ubuntu-latest"]

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@07db5389c99593f11ad7b44463c2d4233066a9b1