name: Code Linting

on:
  push:
    branches: ["main", "master"]

  pull_request:
    branches: ["main", "master", "release-*"]

jobs:
  lint:
    name: Code Linting
    strategy:
      matrix:
        go-version: ["1.17"] # >=1.16 required due to io.ReadAll()
        platform: ["ubuntu-latest"]

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10
    steps:
    - name: Check out code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@b517f99ae23d86ecc4c0dec08dcf48d2336abc29 # v3.1.0