name: Verify Docker Login

on:
  schedule:
    - cron: "5 1 * * *" # daily
    
  workflow_dispatch:

jobs:
  login:
    name: Verify Docker Login
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}